### PR TITLE
Add check for bc

### PR DESCRIPTION
**Pull request by z3bu**

### CODE REVIEW

**Comment by z3bu** [comment]
Hi, I am testing your scripts. My palms got sweaty when I saw I was missing a dependency for script 3!

**Comment by kbeckmann** [comment]
Ah it must be https://github.com/ghidraninja/game-and-watch-backup/blob/main/scripts/flashloader.sh#L16 that uses it. I think we can rewrite this to use printf instead, like `printf '0x%08x' "${size}"`. Then we don't have any dependencies.

**Comment by z3bu** [comment]
Closing. Would you like me to propose a change?

I think the expected behaviour is `printf "$((16#${size}))\n"`

**Comment by kbeckmann** [comment]
Oh you're right, I wasn't thinking properly. ibase=16 with implicit obase=10, i.e. convert from hex to dec. Yeah please do, the fewer dependencies the better!

**Pull request closed without merging**
